### ISSUE TITLE
Better readme, esp for Windows

### ISSUE THREAD

**Issue by Vandivier** [scrapy/quotesbot#5]
I'm receiving the following error trying to `scrapy crawl toscrape-css` on Windows 10:
![image](https://user-images.githubusercontent.com/5559355/36234981-09805f0a-11bc-11e8-9f07-7f56663ec896.png)

Python 3.6.4

This seems to be a matter of poor documentation rather than a real issue, although I may be mistaken.

I did `pip install virtualenv` then `pip install scrapy` then tried to run `scrapy crawl toscrape-css`. What am I missing?

**Comment by torican** [comment]
With all due respect, if you feel the documentation is poor your more than welcome to contribute. This is not a commercial project of course! 

Your issue is not scrapy but your local environment. As per the error - No Module named 'win32api'. A google search for this returns the answer your looking for: 

https://stackoverflow.com/questions/3580855/where-to-find-the-win32api-module-for-python

**Comment by Rednaskel** [comment]
Had same problem. Although it's more python thing than scrapy. 

As Ciwidey Developer mentioned here https://stackoverflow.com/questions/21343774/importerror-no-module-named-win32api

just run `pip install pypiwin32`
